spring:
  datasource:
    url: jdbc:mysql://192.168.0.102:3306/hadoop?characterEncoding=utf-8&amp&serverTimezone=UTC&amp&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

